main: com.b5team.postrequest.Main
name: POSTRequest
version: 1.0
author: bbruno5
description: HTTP/HTTPS POST Request for send data to external PHP server
commands:
  pr:
    description: Calls plgin to send data request
    usage: |
            /<command> <arguments>
    permission: postrequest.pr.send
    permission-message: You don't have permission to do this.
    defalt: op