main: com.b5team.postrequest.Main
name: POSTRequest
version: 1.0.2-SNAPSHOT
author: bbruno5
description: HTTP/HTTPS POST Request for send data to external PHP server
commands:
  pr:
    description: Calls plugin to send data request
    usage: |
            /<command> <arguments>
permissions:
    postrequest.pr.send:
        description: Allows you to use postrequest
        default: op
